# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='null', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default='null', max_length=12),
        ),
    ]
